### ISSUE TITLE
$results variable concat broken in mixed environment (cloud and dedicated)

### ISSUE THREAD

**Issue by leshkinski** [rsWinAutomationSupport/rsMofs#9]
Following DSC error is raised within rsMofs if a mixed cloud and dedicated environment is specified in DDI_rsConfigs:

```
... a non-terminating error was thrown when DSCEngine was executing Test-TargetResource 
on RS_rsMofs DSC resource. FullyQualifiedErrorId is MethodNotFound. ErrorMessage is Method 
invocation failed because [System.Management.Automation.PSObject] does not contain a method named 'op_Addition'..
```

Issue is with: https://github.com/rsWinAutomationSupport/rsMofs/blob/master/DSCResources/RS_rsMofs/RS_rsMofs.psm1#L110
https://github.com/rsWinAutomationSupport/rsMofs/blob/master/DSCResources/RS_rsMofs/RS_rsMofs.psm1#L174

Need to be changed to the following in order to combine both the dedidated and cloud environments in the $results variable:

```
$results = Get-rsDetailsServers | ? {$_.metadata -match $CloudKey} | Select -Property name,id -ExpandProperty metadata | Select name,id,@{Name="rax_dsc_config";Expression=$CloudKey}
```

**Comment by leshkinski** [comment]
fixes issue #9

**Comment by leshkinski** [comment]
pull #10 raised

**Comment by jonathan-madison** [comment]
Merged in, closing.

**Comment by leshkinski** [comment]
Closing issue - changes merged a while ago
